name: ci-cd

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -r requirements.txt
    - name: Commit Lint
      run: |
        pip install gitlint
        gitlint --contrib CT1 --ignore B6 -c general.ignore-merge-commits=true
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint  --rcfile=.pylintrc decide/*.py
    - name: Test with pytest
      run: |
        pytest -vv decide/test --disable-pytest-warnings

  cd:
    needs: ci

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use Python Semantic Release to prepare Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          pip install python-semantic-release
          semantic-release publish
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
